version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: source/requirements.txt
