name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'
    - name: install python dependencies
      run: |
        pip install -r source/requirements.txt
    - name: build html
      run: |
        make html
    - name: archive html
      uses: actions/upload-artifact@v3
      with:
        name: frc-atlas-html
        path: build/html/
        if-no-files-found: error

  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'
    - name: install python dependencies
      run: |
        pip install -r source/requirements.txt
    - name: install latex
      run: |
        sudo apt-fast -y update
        sudo apt-fast install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - name: build pdf
      run: |
        make latexpdf
    - name: archive pdf
      uses: actions/upload-artifact@v3
      with:
        name: frc-atlas-pdf
        path: build/latex/frcatlas.pdf
        if-no-files-found: error
